### PR TITLE
MAINT: Prep 132 wheels branch

### PR DESCRIPTION
**Pull request by tylerjereddy**
Cherry-pick the 4 commits from #55, since that PR has to deal with master branch test failures that are not relevant for the maintenance branches. Also bump `BUILD_COMMIT` to tip of 1.3.x maintenance branch.

We want to prioritize getting this one passing so that we can get 1.3.2 out soon with 3.8 support.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
May need a distributor init for Windows DLL stuff. Mac issue may be harder--Pauli fixed in master by pinning multibuild, but we need HEAD of multibuild for Python 3.8 now.

**Comment by tylerjereddy** [comment]
Cherry-picked what I think we need from #55 -- fingers crossed!

**Comment by tylerjereddy** [comment]
CI is all green so merging -- `1.3.2` should be imminent now that this has been reduced to a regular point release procedure cc @rgommers @charris

**Comment by rgommers** [comment]
Awesome. This PR LGTM!

**Pull request merged**
