### PR TITLE
BLD: update to pybind11 2.4.3, fixes a segfault with SciPy 1.4.0

### PR DESCRIPTION
**Pull request by rgommers**
See https://github.com/scipy/scipy/issues/11237 and
https://github.com/pybind/pybind11/issues/1262 for details.

tl;dr pybind11 is the first version where its symbol names are prefixed
with the GCC (or Clang) version it was compiled with.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Thanks Ralf---if the CI ends up green I'll see what I can about getting this out reasonably soon.

**Comment by rgommers** [comment]
Three failures for `TestFindPeaksCwt.test_find_peaks_exact`, which is unrelated to this PR (I've seen those before, precision issue on `i686`).

**Comment by tylerjereddy** [comment]
Yeah, there's an issue open: https://github.com/scipy/scipy/issues/11095

They're skipped on 1.4.x.

**Comment by tylerjereddy** [comment]
Ok, rest of the CI looks fine, merging so we can move forward with 1.4.1/backport etc.

**Comment by tylerjereddy** [comment]
thanks Ralf

**Pull request merged**
