### PR TITLE
WIP, MAINT: try 3.10rc wheels

### PR DESCRIPTION
**Pull request by tylerjereddy**
* mimic the approach used by NumPy wheels
in: https://github.com/MacPython/numpy-wheels/pull/129

* what could go wrong.. (skip Travis for now)

I'm guessing it is not going to be as easy as just copying what @mattip and @charris did but isn't going to stop me from trying :) Some of our SciPy wheels infra/base images normally used are a bit older perhaps too?

I think even if we do succeed I'd be hesitant to actually put the rc wheel on PyPI vs. just making it available on the anaconda testbed.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
oh, is `config_ilp64.sh` a NumPy specific thing? I may need to dig a little

**Comment by charris** [comment]
Yep, `config_ilp64.sh` was needed to build 64 bit blas wheels. If you stick with 32 bit blas integers you won't need it.

**Comment by tylerjereddy** [comment]
After removing that, `numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.`

**Comment by tylerjereddy** [comment]
We are way behind NumPy in terms of the OpenBLAS version we are shipping with wheels, not sure if related.

**Comment by mattip** [comment]
> We are way behind NumPy in terms of the OpenBLAS version 

You might want to sync `tools/openblas_support.py` with the one in NumPy

**Comment by mattip** [comment]
Maybe connected to downloading a [manylinux1 openblas](https://dev.azure.com/numpy/numpy/_build/results?buildId=18982&view=logs&j=7eb27247-8768-54fc-61e3-aed398435c62&t=e3034194-08eb-5fd3-6e1a-a3b7a962520f&l=277) which later on cannot be linked since it is [missing some gfortran symbols](https://dev.azure.com/numpy/numpy/_build/results?buildId=18982&view=logs&j=7eb27247-8768-54fc-61e3-aed398435c62&t=e3034194-08eb-5fd3-6e1a-a3b7a962520f&l=402)

**Comment by mattip** [comment]
xref scipy/scipy#14316

**Comment by tylerjereddy** [comment]
Makes sense, we got blocked by that linear algebra testing issue for 4-5 versions of OpenBLAS I think, so all the attempts to bump failed. Looks like someone is chipping away at the issue a little at least.

**Comment by charris** [comment]
NumPy will only build manylinux2014 wheels for 1.22. I'm also going to release manylinux2014 3.10 wheels for 1.21.2 so more people can start testing.

**Comment by charris** [comment]
You also need cython >= 0.29.22, but might as well use the latest version 0.29.24.

**Comment by tylerjereddy** [comment]
Ah, I guess I had assumed I needed manylinux 2014, guess I can try removing that at least.

**Comment by mattip** [comment]
manylinux 2014 is OK. There are two sides to moving off manylinux1 and manylinux2010:
- Will people be able to use `pip` to install the manylinux2014 wheel (yes, since python3.10 comes with pip-21.1.3 which supports manyinux2014)?
- does the glibc in the oldeset distro supported conform to manylinux2014/glibc2.17 (yes, since CenOS6 (manylinux2010, glibc 2.15) is [EOL](https://github.com/mayeut/pep600_compliance#acceptable-distros-to-build-wheels)

**Comment by tylerjereddy** [comment]
I'll close this--I think @tupui is going to try adding 3.10 now at @rgommers suggestion--for some reason I thought we might have some issues that we'd been avoiding with manylinux version bump but hopefully I"m wrong

**Pull request closed without merging**
