### PR TITLE
remove last vestiges of manylinux1

### PR DESCRIPTION
**Pull request by h-vetinari**
For https://github.com/scipy/scipy/pull/13347

### CODE REVIEW

**Comment by h-vetinari** [comment]
The reason https://github.com/MacPython/scipy-wheels/pull/141/commits/45153694b391689e5212655ef2d9e9f4822aa4ce only removes the line is that - AFAIU - the manylinux-versions for each job are already set in [`azure-pipelines.yml`](https://github.com/MacPython/scipy-wheels/blob/master/azure-pipelines.yml#L25)

**Comment by h-vetinari** [comment]
The failing CI on travis/appveyor will be taken care of by https://github.com/scipy/scipy/pull/15053.

**Review by tylerjereddy — APPROVED** [review]
Seems "ok" thanks, the CI failures are not related.

I haven't had issues with the `timeoutInMinutes` for Azure so far, but "ok." Appveyor is the real turtle in the process at the moment.

**Comment by h-vetinari** [comment]
Thanks!

> Seems "ok" thanks, the CI failures are not related.

There's a scipy-PR to take care of this

> I haven't had issues with the `timeoutInMinutes` for Azure so far, but "ok."

Yeah, some azure agents are slower than others. Long runtimes are annoying, but I'd say it's even more annoying when the only "failure" was that things took longer than usual, hence me bumping the timeout quite generously.

**Pull request merged**
