### PR TITLE
BLD: update to pybind11 2.4.3, fixes a segfault with SciPy 1.4.0

### PR DESCRIPTION
**Pull request by tylerjereddy**
Wheels repo backport of #60 in preparation for SciPy `1.4.1`.

### CODE REVIEW

**Comment by rgommers** [comment]
Merged, thanks @tylerjereddy. No need for this simply commit to run 5x for every PR, every merge, and then again for v1.4.1

**Comment by pv** [comment]
The openblas-libs rebuild just a moment ago changed openblas hashes, so they'd need to be updated.

**Comment by rgommers** [comment]
Is that for the 64-bit BLAS? If so, wouldn't it be better to leave that out of v1.4.1?

**Comment by tylerjereddy** [comment]
The regular OpenBLAS got rebuilt as well as a side-effect I think, because I could not cancel those jobs. I probably should have just deleted the matrix entries but I was busy I guess & want to quickly provide those for the NumPy testing stuff.

**Comment by pv** [comment]
Yes, the openblas-libs setup is a bit dangerous vs. overwriting existing artifacts (and several projects rely on those). Could maybe be better to add some "dev" env flag on the master branch, and forbid the wheel uploader from replacing artifacts on non-dev builds.

**Comment by tylerjereddy** [comment]
In addition to the hashes I also see one fail for `scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver`.

**Pull request merged**
