### PR TITLE
MAINT: multibuild new repo update

### PR DESCRIPTION
**Pull request by tylerjereddy**
* point multibuild at the new repo location
and use latest `devel`

### CODE REVIEW

**Comment by charris** [comment]
You should also be able to build thin macosx wheels for Python 3.10.

**Comment by tylerjereddy** [comment]
that's true, and indeed I'm attempting that for the backport in gh-135. I wasn't actually sure if we want to expand our `master` branch offerings just yet or if we might still aim for `universal2` on `master`; certainly for that backport PR I've set to thin x86_64 Mac OS Python 3.10 only

**Comment by rgommers** [comment]
We should also do thin wheels on master - thin wheels are the preferred format, universal2 is kind of a hack that we could leave out at some point.

**Comment by charris** [comment]
I'm going to speculate that the problems come from `#include <numpy/ndarrayobject.h>`.

**Comment by tylerjereddy** [comment]
The Python 3.8 Windows permission failure in `C:\Python38-x64\lib\site-packages\scipy\integrate\tests\test__quad_vec.py:127: in test_quad_vec_pool_args` is super annoying--that's affecting the backport/1.7.2 release as well..

**Comment by tylerjereddy** [comment]
ok, well we need to point to the new `multibuild` repo location moving forward anyway, so I'll put this in

There is indeed some more stuff to do with thin wheels here and in the release branch..

**Pull request merged**
