### PR TITLE
MAINT: master->main refs

### PR DESCRIPTION
**Pull request by tylerjereddy**
* there are no plans I'm aware of to change `master` to
`main` on the wheels repo, but I've started seeing cron
errors related to `master` checkouts of the main repo

* so, try to fixup cases where `master` is incorrectly used
to reference the main SciPy repo, but leave `master` in for
those cases where we are referring to the wheels repo proper
(at least for now)

* reference CI failure:
https://app.travis-ci.com/github/MacPython/scipy-wheels/jobs/558549551

* I do realize we plan to replace the wheels infrastructure here eventually, but until then...

### CODE REVIEW

**Comment by rgommers** [comment]
Appveyor failure is Pythran, the Linux 32-bit wheel may be related since this PR pulls in a newer `numpy.distutils` version.

**Comment by tylerjereddy** [comment]
Close/re-open--let's see where we stand here a few months later. I'm almost certain we'll need more wheels repo `master` adjustments than this before I can tackle `1.9.0rc1`, but it is a start and I need to see what fails beyond the currently nightly crons that get stuck at `master` vs. `main` issues per https://app.travis-ci.com/github/MacPython/scipy-wheels/jobs/571740251

**Comment by tylerjereddy** [comment]
For the Windows failures I'll try pinning `setuptools`, which is pinned on `v1.8.x` but not on `master` of this repo.

I'm also not going to be surprised if there is yet another complication with this merged in now: https://github.com/scipy/scipy/pull/16335

**Comment by tylerjereddy** [comment]
@mdhaber @mckib2 I'm seeing a failure to compile `scipy\_lib\highs\src\simplex\HEkkDual.obj` on Windows. From a careful dissection of the differences in the compile line for this source file here vs. in the main repo, the best explanation I can come up with is that we are using Visual Studio 2017 here in the wheels repo, which is lagging behind the main repo at 2019.

Here's an image of a colored "word diff" between the two compile lines, and it seems almost identical beyond the tooling versions, so I'll give the bump a try...
image

**Comment by tylerjereddy** [comment]
I may need to ask for some more Travis credits too based on the banner I'm seeing there this evening..

**Comment by tylerjereddy** [comment]
Ah, for appveyor I see stuff hardcoded to `C:\Program Files (x86)\Microsoft Visual Studio 14.0` in a few places, and one of the directory listings doesn't necessarily show the new version (unless it is the unversioned listing):

```
05/27/2022  03:35 PM    <DIR>          Microsoft Visual Studio
05/27/2022  10:39 PM    <DIR>          Microsoft Visual Studio 10.0
05/27/2022  10:39 PM    <DIR>          Microsoft Visual Studio 11.0
05/27/2022  10:39 PM    <DIR>          Microsoft Visual Studio 12.0
05/27/2022  04:13 PM    <DIR>          Microsoft Visual Studio 14.0
05/27/2022  03:53 PM    <DIR>          Microsoft Web Tools

```

I may need to debug that on a fork or something. The usage of both years and numbers for versions doesn't make things clearer either.

**Comment by tylerjereddy** [comment]
32-bit Windows jobs are successfully building with VS 2019 now (thought failing a few tests), but 64-bit Windows jobs need some checking.

**Comment by tylerjereddy** [comment]
The Travis CI team filled up our credits again but I've temporarily disabled Travis CI here while I iterate.

The most annoying issues at the moment is that the Linux 32-bit jobs seemed to recently switch to basically running forever at the test stage and ignoring timeout cancellation requests, along with not providing any usable log output. I'm hoping that changes with the latest push, but if it doesn't I may need to check this in a 32-bit container locally.

**Comment by tylerjereddy** [comment]
Another thing to consider is that stuff like this may not be forward compatible now that I've bumped the compiler version:
`copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\msvcp140.dll" ` ? 

I suspect I should try to copy in the DLL from the matching version of Visual Studio.

**Comment by tylerjereddy** [comment]
I'll iterate/debug the DLL updates on my fork until that works: https://github.com/tylerjereddy/scipy-wheels/pull/3

**Comment by tylerjereddy** [comment]
The DLL updates have been cherry-picked in. The 32-bit linux test-time hang/infinite run I'm still investigating.

**Comment by tylerjereddy** [comment]
@isuruf @matthew-brett @charris @mattip have you seen this issue where the 32-bit Linux jobs literally run for days instead of timing out and giving useful output? https://github.com/MacPython/scipy-wheels/runs/6785487807

image

**Comment by tylerjereddy** [comment]
Appveyor was fully passing so I've temporarily disabled that and also simplified the Azure matrix to focus on debugging the 32-bit Linux builds that keep running indefinitely.

As a start, I'll see what happens if I bump `DOCKER_TEST_IMAGE` to a newer base image than `xenial`. The main repo is using a newer base image I think with `i386/ubuntu:bionic` in Azure over there. I'm expecting this to fail though since no such image exists at https://hub.docker.com/u/multibuild. Hopefully it will not run indefinitely though--the current status is that the test stage will not even timeout with `DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"`, it will just run forever with no feedback, which is rather hard to debug of course.

If I finally see a proper error/termination with that change, then I'll probably have to switch the image back and experiment a bit. I could try bumping the `multibuild` sumbodule just in case I guess.

**Comment by tylerjereddy** [comment]
Ok, using an invalid `DOCKER_TEST_IMAGE` did indeed cause a proper failure for the 32-bit jobs, rather than running forever. I've switched `DOCKER_TEST_IMAGE` back to the only option we have for 32-bit Linux, but also updated `multibuild` submodule to the latest hash to see if that might help.

It feels like a bit of a stretch, but worth a try.

**Comment by tylerjereddy** [comment]
Looks like the "hang" happens fairly early in the 32-bit Linux testsuite:

image

One option then is to use a higher verbosity test run to see which part of the suite is visited to get a hint where the freeze happens.

Before I do that though, let me temporarily point this branch at the tip of `maintenance/1.9.x` to see if that avoids the hang--if it does I would gladly avoid dealing with it on `main`. If it still hangs after that, then I'll need to narrow the hang down a bit more.

**Comment by tylerjereddy** [comment]
Pointing to the tip of the maintenance branch allowed the 32-bit Linux job with Python 3.9 to fail the testsuite in the normal way, but `3.8` is running indefinitely even on that branch.

**Comment by tylerjereddy** [comment]
Watching the problematic 32-bit Linux jobs more carefully, in real time, I see 20+ minutes stuck here for both Python 3.8/3.9:

`3.8`:

```
+ python -m pip install /io/wheelhouse/SciPy-1.10.0.dev0+0.da7a602-cp38-cp38-manylinux_2_12_i686.manylinux2010_i686.whl
Processing ./wheelhouse/SciPy-1.10.0.dev0+0.da7a602-cp38-cp38-manylinux_2_12_i686.manylinux2010_i686.whl
Collecting numpy>=1.19.5
  Downloading numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517): started
```

`3.9`:

```
+ python -m pip install /io/wheelhouse/SciPy-1.10.0.dev0+0.da7a602-cp39-cp39-manylinux_2_12_i686.manylinux2010_i686.whl
Processing ./wheelhouse/SciPy-1.10.0.dev0+0.da7a602-cp39-cp39-manylinux_2_12_i686.manylinux2010_i686.whl
Collecting numpy>=1.19.5
  Downloading numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies: started
```

**Comment by tylerjereddy** [comment]
Ok, both jobs stuck there for 40 minutes now, better touch base with NumPy team re: this getting built from source and taking forever/hanging vs. the binary availble in `1.22.x` series.

**Comment by charris** [comment]
Have you tried with manylinux2014?

**Comment by tylerjereddy** [comment]
Haven't tried that, let me see if Matti's suggestion of `install_wheel --only-binary :numpy:` allows me to squeak by first.

**Comment by tylerjereddy** [comment]
That didn't work, but a generic `--prefer-binary` did, so I'll proceed with cleaning this PR up a bit now.

**Comment by tylerjereddy** [comment]
I think this is in pretty good shape now @rgommers. Here's a summary of what has changed:

- `master` -> `main` in a bunch of places for SciPy and NumPy (distutils); latter shim may not even be needed anymore but things seem "ok" so..
- `appveyor.yml` gets a bigger set of changes:
  - it needed some newer C++ things, so the base image is bumped to a newer Visual Studio version (already done in the main repo quite some time ago, albeit on Azure instead)
  - bump build-time version of NumPy to `1.18.5` (not using `pyproject.toml` for Windows builds here yet); not going as high as `main` yet to facilitate the branching here
  - DLL/mingw toolchain adjustments for VS 2019
-  the `install_wheel` command has been adjusted to `install_wheel --prefer-binary` so that the 32-bit Linux Azure jobs don't hang/run for 40+ minutes trying to build NumPy `1.22.4` from source; other command suggestions failed for whatever reason, maybe because installing directly from a local wheel file is slightly different..
- bump `multibuild` submodule to latest upstream version; no real benefit to this--it was one of many attempts to deal with the 32-bit Linux wheel issues, but I'm not sure it is worth reverting either since we usually bump liberally there anyway


What is still failing in CI?

- 32-bit Linux wheels have 3 failures, 2 of which are handled by https://github.com/scipy/scipy/pull/16390, the other is new as of today so I'm less worried about it for branching purposes
- that's it, everything else is passing, which is a huge change from where we were before this PR (and with the help of several recent PRs on `main` in main repo)

**Review by rgommers — APPROVED** [review]
Thanks Tyler! Everything in this PR LGTM, and I agree that the test failures on the two 32-bit Linux jobs are not a blocker. In it goes

**Pull request merged**
